#[Backend]
backend = "hyprsunset"
transition_mode = "static"

#[Smoothing]
smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

#[Static config]
static_temp = 6500
static_gamma = 100
